  
//Detector

/*
1= Bumper Left
2= Bumper Right
3= DISTANCE_SENSOR_LEFT
4= DISTANCE_SENSOR_RIGHT
5= DISTANCE_SENSOR_FRONT_LEFT
6= DISTANCE_SENSOR_FRONT_RIGHT




*/


int detector_value;
 
  void detector(){   
  if (      BUMPER_LEFT&&  BUMPER_RIGHT&&  DISTANCE_SENSOR_LEFT&&  DISTANCE_SENSOR_RIGHT&&  DISTANCE_SENSOR_FRONT_LEFT&&  DISTANCE_SENSOR_FRONT_RIGHT)detector_value=1;        
  if (      BUMPER_LEFT&&  BUMPER_RIGHT&&  DISTANCE_SENSOR_LEFT&&  DISTANCE_SENSOR_RIGHT&&  DISTANCE_SENSOR_FRONT_LEFT&& !DISTANCE_SENSOR_FRONT_RIGHT)detector_value=2;            
  if (      BUMPER_LEFT&&  BUMPER_RIGHT&&  DISTANCE_SENSOR_LEFT&&  DISTANCE_SENSOR_RIGHT&& !DISTANCE_SENSOR_FRONT_LEFT&&  DISTANCE_SENSOR_FRONT_RIGHT)detector_value=3;          
  if (      BUMPER_LEFT&&  BUMPER_RIGHT&&  DISTANCE_SENSOR_LEFT&& !DISTANCE_SENSOR_RIGHT&&  DISTANCE_SENSOR_FRONT_LEFT&&  DISTANCE_SENSOR_FRONT_RIGHT)detector_value=4;      
  if (      BUMPER_LEFT&&  BUMPER_RIGHT&& !DISTANCE_SENSOR_LEFT&&  DISTANCE_SENSOR_RIGHT&&  DISTANCE_SENSOR_FRONT_LEFT&&  DISTANCE_SENSOR_FRONT_RIGHT)detector_value=5;     
  if (      BUMPER_LEFT&& !BUMPER_RIGHT&&  DISTANCE_SENSOR_LEFT&&  DISTANCE_SENSOR_RIGHT&&  DISTANCE_SENSOR_FRONT_LEFT&&  DISTANCE_SENSOR_FRONT_RIGHT)detector_value=6;     
  if (     !BUMPER_LEFT&&  BUMPER_RIGHT&&  DISTANCE_SENSOR_LEFT&&  DISTANCE_SENSOR_RIGHT&&  DISTANCE_SENSOR_FRONT_LEFT&&  DISTANCE_SENSOR_FRONT_RIGHT)detector_value=7;    
  if (      BUMPER_LEFT&&  BUMPER_RIGHT&&  DISTANCE_SENSOR_LEFT&&  DISTANCE_SENSOR_RIGHT&& !DISTANCE_SENSOR_FRONT_LEFT&& !DISTANCE_SENSOR_FRONT_RIGHT)detector_value=8;      
  if (      BUMPER_LEFT&&  BUMPER_RIGHT&&  DISTANCE_SENSOR_LEFT&& !DISTANCE_SENSOR_RIGHT&& !DISTANCE_SENSOR_FRONT_LEFT&&  DISTANCE_SENSOR_FRONT_RIGHT)detector_value=9; 
  if (      BUMPER_LEFT&&  BUMPER_RIGHT&& !DISTANCE_SENSOR_LEFT&& !DISTANCE_SENSOR_RIGHT&&  DISTANCE_SENSOR_FRONT_LEFT&&  DISTANCE_SENSOR_FRONT_RIGHT)detector_value=10;  
  if (      BUMPER_LEFT&& !BUMPER_RIGHT&& !DISTANCE_SENSOR_LEFT&&  DISTANCE_SENSOR_RIGHT&&  DISTANCE_SENSOR_FRONT_LEFT&&  DISTANCE_SENSOR_FRONT_RIGHT)detector_value=11;           
  if (     !BUMPER_LEFT&& !BUMPER_RIGHT&&  DISTANCE_SENSOR_LEFT&&  DISTANCE_SENSOR_RIGHT&&  DISTANCE_SENSOR_FRONT_LEFT&&  DISTANCE_SENSOR_FRONT_RIGHT)detector_value=12;     
  if (      BUMPER_LEFT&&  BUMPER_RIGHT&&  DISTANCE_SENSOR_LEFT&& !DISTANCE_SENSOR_RIGHT&& !DISTANCE_SENSOR_FRONT_LEFT&& !DISTANCE_SENSOR_FRONT_RIGHT)detector_value=13;                            
  if (      BUMPER_LEFT&&  BUMPER_RIGHT&& !DISTANCE_SENSOR_LEFT&& !DISTANCE_SENSOR_RIGHT&& !DISTANCE_SENSOR_FRONT_LEFT&&  DISTANCE_SENSOR_FRONT_RIGHT)detector_value=14;      
  if (      BUMPER_LEFT&&  BUMPER_RIGHT&& !DISTANCE_SENSOR_LEFT&& !DISTANCE_SENSOR_RIGHT&&  DISTANCE_SENSOR_FRONT_LEFT&&  DISTANCE_SENSOR_FRONT_RIGHT)detector_value=15;       
  if (     !BUMPER_LEFT&& !BUMPER_RIGHT&& !DISTANCE_SENSOR_LEFT&&  DISTANCE_SENSOR_RIGHT&&  DISTANCE_SENSOR_FRONT_LEFT&&  DISTANCE_SENSOR_FRONT_RIGHT)detector_value=16;   
  if (      BUMPER_LEFT&&  BUMPER_RIGHT&& !DISTANCE_SENSOR_LEFT&& !DISTANCE_SENSOR_RIGHT&& !DISTANCE_SENSOR_FRONT_LEFT&& !DISTANCE_SENSOR_FRONT_RIGHT)detector_value=17;   
  if (      BUMPER_LEFT&& !BUMPER_RIGHT&& !DISTANCE_SENSOR_LEFT&& !DISTANCE_SENSOR_RIGHT&& !DISTANCE_SENSOR_FRONT_LEFT&&  DISTANCE_SENSOR_FRONT_RIGHT)detector_value=18;          
  if (     !BUMPER_LEFT&& !BUMPER_RIGHT&& !DISTANCE_SENSOR_LEFT&& !DISTANCE_SENSOR_RIGHT&&  DISTANCE_SENSOR_FRONT_LEFT&&  DISTANCE_SENSOR_FRONT_RIGHT)detector_value=19;   
  if (      BUMPER_LEFT&& !BUMPER_RIGHT&& !DISTANCE_SENSOR_LEFT&& !DISTANCE_SENSOR_RIGHT&& !DISTANCE_SENSOR_FRONT_LEFT&& !DISTANCE_SENSOR_FRONT_RIGHT)detector_value=20;   
  if (     !BUMPER_LEFT&&  BUMPER_RIGHT&& !DISTANCE_SENSOR_LEFT&& !DISTANCE_SENSOR_RIGHT&& !DISTANCE_SENSOR_FRONT_LEFT&&  DISTANCE_SENSOR_FRONT_RIGHT)detector_value=21;    
  if (     !BUMPER_LEFT&& !BUMPER_RIGHT&& !DISTANCE_SENSOR_LEFT&& !DISTANCE_SENSOR_RIGHT&& !DISTANCE_SENSOR_FRONT_LEFT&& !DISTANCE_SENSOR_FRONT_RIGHT)detector_value=22;        
  if (      BUMPER_LEFT&&  BUMPER_RIGHT&&  DISTANCE_SENSOR_LEFT&& !DISTANCE_SENSOR_RIGHT&&  DISTANCE_SENSOR_FRONT_LEFT&& !DISTANCE_SENSOR_FRONT_RIGHT)detector_value=23;            
  if (      BUMPER_LEFT&&  BUMPER_RIGHT&&  DISTANCE_SENSOR_LEFT&& !DISTANCE_SENSOR_RIGHT&&  DISTANCE_SENSOR_FRONT_LEFT&& !DISTANCE_SENSOR_FRONT_RIGHT)detector_value=24;          
  if (      BUMPER_LEFT&& !BUMPER_RIGHT&&  DISTANCE_SENSOR_LEFT&& !DISTANCE_SENSOR_RIGHT&&  DISTANCE_SENSOR_FRONT_LEFT&&  DISTANCE_SENSOR_FRONT_RIGHT)detector_value=25;      
  if (     !BUMPER_LEFT&&  BUMPER_RIGHT&& !DISTANCE_SENSOR_LEFT&&  DISTANCE_SENSOR_RIGHT&&  DISTANCE_SENSOR_FRONT_LEFT&&  DISTANCE_SENSOR_FRONT_RIGHT)detector_value=26;     
  if (      BUMPER_LEFT&&  BUMPER_RIGHT&& !DISTANCE_SENSOR_LEFT&&  DISTANCE_SENSOR_RIGHT&&  DISTANCE_SENSOR_FRONT_LEFT&& !DISTANCE_SENSOR_FRONT_RIGHT)detector_value=27;     
  if (      BUMPER_LEFT&& !BUMPER_RIGHT&&  DISTANCE_SENSOR_LEFT&&  DISTANCE_SENSOR_RIGHT&& !DISTANCE_SENSOR_FRONT_LEFT&&  DISTANCE_SENSOR_FRONT_RIGHT)detector_value=28;    
  if (     !BUMPER_LEFT&&  BUMPER_RIGHT&&  DISTANCE_SENSOR_LEFT&& !DISTANCE_SENSOR_RIGHT&&  DISTANCE_SENSOR_FRONT_LEFT&&  DISTANCE_SENSOR_FRONT_RIGHT)detector_value=29;      
  if (      BUMPER_LEFT&& !BUMPER_RIGHT&&  DISTANCE_SENSOR_LEFT&&  DISTANCE_SENSOR_RIGHT&&  DISTANCE_SENSOR_FRONT_LEFT&& !DISTANCE_SENSOR_FRONT_RIGHT)detector_value=30; 
  if (     !BUMPER_LEFT&&  BUMPER_RIGHT&&  DISTANCE_SENSOR_LEFT&&  DISTANCE_SENSOR_RIGHT&& !DISTANCE_SENSOR_FRONT_LEFT&&  DISTANCE_SENSOR_FRONT_RIGHT)detector_value=31;  
  if (     !BUMPER_LEFT&&  BUMPER_RIGHT&&  DISTANCE_SENSOR_LEFT&&  DISTANCE_SENSOR_RIGHT&&  DISTANCE_SENSOR_FRONT_LEFT&& !DISTANCE_SENSOR_FRONT_RIGHT)detector_value=32;           
  if (     !BUMPER_LEFT&& !BUMPER_RIGHT&& !DISTANCE_SENSOR_LEFT&& !DISTANCE_SENSOR_RIGHT&&  DISTANCE_SENSOR_FRONT_LEFT&& !DISTANCE_SENSOR_FRONT_RIGHT)detector_value=33;     
  if (     !BUMPER_LEFT&& !BUMPER_RIGHT&& !DISTANCE_SENSOR_LEFT&&  DISTANCE_SENSOR_RIGHT&& !DISTANCE_SENSOR_FRONT_LEFT&& !DISTANCE_SENSOR_FRONT_RIGHT)detector_value=34;                            
  if (     !BUMPER_LEFT&& !BUMPER_RIGHT&&  DISTANCE_SENSOR_LEFT&& !DISTANCE_SENSOR_RIGHT&& !DISTANCE_SENSOR_FRONT_LEFT&& !DISTANCE_SENSOR_FRONT_RIGHT)detector_value=35;      
  if (     !BUMPER_LEFT&&  BUMPER_RIGHT&& !DISTANCE_SENSOR_LEFT&& !DISTANCE_SENSOR_RIGHT&& !DISTANCE_SENSOR_FRONT_LEFT&& !DISTANCE_SENSOR_FRONT_RIGHT)detector_value=36;       
  if (     !BUMPER_LEFT&& !BUMPER_RIGHT&& !DISTANCE_SENSOR_LEFT&&  DISTANCE_SENSOR_RIGHT&&  DISTANCE_SENSOR_FRONT_LEFT&& !DISTANCE_SENSOR_FRONT_RIGHT)detector_value=37;   
  if (     !BUMPER_LEFT&& !BUMPER_RIGHT&&  DISTANCE_SENSOR_LEFT&&  DISTANCE_SENSOR_RIGHT&& !DISTANCE_SENSOR_FRONT_LEFT&& !DISTANCE_SENSOR_FRONT_RIGHT)detector_value=38;   
  if (     !BUMPER_LEFT&&  BUMPER_RIGHT&&  DISTANCE_SENSOR_LEFT&& !DISTANCE_SENSOR_RIGHT&& !DISTANCE_SENSOR_FRONT_LEFT&& !DISTANCE_SENSOR_FRONT_RIGHT)detector_value=39;          
  if (     !BUMPER_LEFT&&  BUMPER_RIGHT&& !DISTANCE_SENSOR_LEFT&&  DISTANCE_SENSOR_RIGHT&& !DISTANCE_SENSOR_FRONT_LEFT&&  DISTANCE_SENSOR_FRONT_RIGHT)detector_value=40;   
  if (      BUMPER_LEFT&& !BUMPER_RIGHT&&  DISTANCE_SENSOR_LEFT&& !DISTANCE_SENSOR_RIGHT&&  DISTANCE_SENSOR_FRONT_LEFT&& !DISTANCE_SENSOR_FRONT_RIGHT)detector_value=41;   
  if (     !BUMPER_LEFT&&  BUMPER_RIGHT&&  DISTANCE_SENSOR_LEFT&& !DISTANCE_SENSOR_RIGHT&& !DISTANCE_SENSOR_FRONT_LEFT&&  DISTANCE_SENSOR_FRONT_RIGHT)detector_value=42;   
  if (      BUMPER_LEFT&& !BUMPER_RIGHT&& !DISTANCE_SENSOR_LEFT&&  DISTANCE_SENSOR_RIGHT&&  DISTANCE_SENSOR_FRONT_LEFT&& !DISTANCE_SENSOR_FRONT_RIGHT)detector_value=43;          
  if (     !BUMPER_LEFT&& !BUMPER_RIGHT&&  DISTANCE_SENSOR_LEFT&& !DISTANCE_SENSOR_RIGHT&&  DISTANCE_SENSOR_FRONT_LEFT&& !DISTANCE_SENSOR_FRONT_RIGHT)detector_value=44;      
  if (     !BUMPER_LEFT&& !BUMPER_RIGHT&&  DISTANCE_SENSOR_LEFT&& !DISTANCE_SENSOR_RIGHT&& !DISTANCE_SENSOR_FRONT_LEFT&&  DISTANCE_SENSOR_FRONT_RIGHT)detector_value=45;     
  if (     !BUMPER_LEFT&&  BUMPER_RIGHT&& !DISTANCE_SENSOR_LEFT&& !DISTANCE_SENSOR_RIGHT&&  DISTANCE_SENSOR_FRONT_LEFT&& !DISTANCE_SENSOR_FRONT_RIGHT)detector_value=46;     
  if (     !BUMPER_LEFT&&  BUMPER_RIGHT&& !DISTANCE_SENSOR_LEFT&& !DISTANCE_SENSOR_RIGHT&& !DISTANCE_SENSOR_FRONT_LEFT&&  DISTANCE_SENSOR_FRONT_RIGHT)detector_value=47;    
  if (      BUMPER_LEFT&& !BUMPER_RIGHT&& !DISTANCE_SENSOR_LEFT&& !DISTANCE_SENSOR_RIGHT&&  DISTANCE_SENSOR_FRONT_LEFT&& !DISTANCE_SENSOR_FRONT_RIGHT)detector_value=48;      
  if (      BUMPER_LEFT&& !BUMPER_RIGHT&& !DISTANCE_SENSOR_LEFT&&  DISTANCE_SENSOR_RIGHT&& !DISTANCE_SENSOR_FRONT_LEFT&& !DISTANCE_SENSOR_FRONT_RIGHT)detector_value=49; 
  if (     !BUMPER_LEFT&& !BUMPER_RIGHT&&  DISTANCE_SENSOR_LEFT&&  DISTANCE_SENSOR_RIGHT&& !DISTANCE_SENSOR_FRONT_LEFT&&  DISTANCE_SENSOR_FRONT_RIGHT)detector_value=50;  
  if (      BUMPER_LEFT&& !BUMPER_RIGHT&& !DISTANCE_SENSOR_LEFT&&  DISTANCE_SENSOR_RIGHT&&  DISTANCE_SENSOR_FRONT_LEFT&& !DISTANCE_SENSOR_FRONT_RIGHT)detector_value=51;           
  if (     !BUMPER_LEFT&& !BUMPER_RIGHT&&  DISTANCE_SENSOR_LEFT&&  DISTANCE_SENSOR_RIGHT&& !DISTANCE_SENSOR_FRONT_LEFT&&  DISTANCE_SENSOR_FRONT_RIGHT)detector_value=52;     
  if (     !BUMPER_LEFT&& !BUMPER_RIGHT&&  DISTANCE_SENSOR_LEFT&& !DISTANCE_SENSOR_RIGHT&&  DISTANCE_SENSOR_FRONT_LEFT&&  DISTANCE_SENSOR_FRONT_RIGHT)detector_value=53;                            
  if (     !BUMPER_LEFT&& !BUMPER_RIGHT&& !DISTANCE_SENSOR_LEFT&&  DISTANCE_SENSOR_RIGHT&& !DISTANCE_SENSOR_FRONT_LEFT&&  DISTANCE_SENSOR_FRONT_RIGHT)detector_value=54;      
  if (      BUMPER_LEFT&&  BUMPER_RIGHT&& !DISTANCE_SENSOR_LEFT&& !DISTANCE_SENSOR_RIGHT&&  DISTANCE_SENSOR_FRONT_LEFT&& !DISTANCE_SENSOR_FRONT_RIGHT)detector_value=55;       
  if (     !BUMPER_LEFT&&  BUMPER_RIGHT&&  DISTANCE_SENSOR_LEFT&&  DISTANCE_SENSOR_RIGHT&& !DISTANCE_SENSOR_FRONT_LEFT&& !DISTANCE_SENSOR_FRONT_RIGHT)detector_value=56;   
  if (     !BUMPER_LEFT&&  BUMPER_RIGHT&& !DISTANCE_SENSOR_LEFT&&  DISTANCE_SENSOR_RIGHT&& !DISTANCE_SENSOR_FRONT_LEFT&& !DISTANCE_SENSOR_FRONT_RIGHT)detector_value=57;   
  if (      BUMPER_LEFT&&  BUMPER_RIGHT&& !DISTANCE_SENSOR_LEFT&&  DISTANCE_SENSOR_RIGHT&& !DISTANCE_SENSOR_FRONT_LEFT&& !DISTANCE_SENSOR_FRONT_RIGHT)detector_value=58;          
  if (      BUMPER_LEFT&& !BUMPER_RIGHT&&  DISTANCE_SENSOR_LEFT&& !DISTANCE_SENSOR_RIGHT&& !DISTANCE_SENSOR_FRONT_LEFT&& !DISTANCE_SENSOR_FRONT_RIGHT)detector_value=59;   
  if (      BUMPER_LEFT&& !BUMPER_RIGHT&&  DISTANCE_SENSOR_LEFT&&  DISTANCE_SENSOR_RIGHT&& !DISTANCE_SENSOR_FRONT_LEFT&& !DISTANCE_SENSOR_FRONT_RIGHT)detector_value=60;   
  if (     !BUMPER_LEFT&&  BUMPER_RIGHT&& !DISTANCE_SENSOR_LEFT&& !DISTANCE_SENSOR_RIGHT&&  DISTANCE_SENSOR_FRONT_LEFT&&  DISTANCE_SENSOR_FRONT_RIGHT)detector_value=61;        
        
  if (     (iTime/52.2)<10)detector_value=65;  
    
  
  
  
  } 